name: Process Koios Data

on:
  # You can adjust the trigger as needed. For example, you can run this on a schedule.
  workflow_dispatch: 

jobs:
  process:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Extract payment_address and save to parties1.json
      run: |
        jq '[.[] | .payment_address]' KoiosAddressList.json > parties1.json

    - name: Count total quantity and save to total_tickets_sold.json
      run: |
        TOTAL_QUANTITY=$(jq 'reduce .[] as $item (0; . + ($item.quantity | tonumber))' KoiosAddressList.json)
        echo "{\"total_tickets_sold\": $TOTAL_QUANTITY}" > total_tickets_sold.json

    - name: Commit and push the changes
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        git add parties1.json total_tickets_sold.json
        git commit -m "Update processed data" || echo "No changes to commit"
        git push origin HEAD:main || echo "No changes to push"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
